service: where-is-my-nft

plugins:
  - serverless-openapi-documenter
  # Plugin responsible for translating typescript to javascript
  - serverless-esbuild
  # Plugin responsible for deleting past lambda version
  - serverless-prune-plugin
  # Plugin for running the server locally and testing
  - serverless-offline

package:
  individually: true
  exclude:
    - .serverless/**
    - .git/**
  include:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
    - "node_modules/.prisma/client/schema.prisma"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage}
  region: us-east-1
  environment:
    STAGE: ${self:custom.stage}
    DATABASE_URL: postgresql://${self:custom.postgres.username}:${self:custom.postgres.password}@${self:custom.postgres.host}:5432/${self:custom.postgres.dbName}
    databaseUser: ${self:custom.postgres.username}
    databaseName: ${self:custom.postgres.dbName}
    databasePassword: ${self:custom.postgres.password}
    databaseHost: ${self:custom.postgres.host}
  stackTags:
    service: where-is-my-nft-backend

custom:
  esbuild:
    target: "node16"
    bundle: true
    minify: false
    packagerOptions:
      scripts:
        - npx prisma generate
  documentation: ${file(sls/documentation/serverless.doc.yml):documentation}

  stage: ${opt:stage, 'dev'}
  prune:
    automatic: true
    number: 1
  postgres:
    dbName: postgres
    username: nft
    password: ${ssm:${self:custom.rdsSecretName}}
    maxConnections:
      dev: 100
    dbInstanceClass:
      dev: db.t4g.micro
    allocatedStorage:
      dev: "20"
    vpcCIDR: 10
    host: ${ssm:${self:custom.rdsHostSecretPath}}
  rdsSecretName: /rds/password
  rdsHostSecretPath: /rds/host-${self:custom.stage}
  bucketName: where-is-my-nft-swagger-${self:custom.stage}

functions:
  - ${file(sls/functions/api/getAccount.yml)}
  - ${file(sls/functions/api/updateAccount.yml)}

resources:
  # RDS
  - ${file(sls/resources/rds/database.yml)}
  - ${file(sls/resources/rds/vpc.yml)}
  # PARAMETER STORE
  - ${file(sls/resources/parameter/database.yml)}
  # S3
  - ${file(sls/resources/s3/bucketPolicy.yml)}
  - ${file(sls/resources/s3/swaggerBucket.yml)}
