name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          sudo npm i -g serverless@3.6.0
          sls deploy -s dev --verbose
          sls openapi generate
          aws s3api put-object --bucket where-is-my-nft-swagger-dev --key apis/core --content-type "application/json" --body openapi.json --debug
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.1.3.tar.gz
          tar -zxf v4.1.3.tar.gz
          cp swagger/* swagger-ui-4.1.3/dist/
          cd swagger-ui-4.1.3/dist/
          aws s3 sync . s3://where-is-my-nft-swagger-dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        name: Deploy to AWS
